language: go

go:
  - "1.11.1"

go_import_path: github.com/kevinwmiller/digidoc

branches:
  only:
  - master
  - development

stages:
  - setup
  - compile
  - test

env:
  - GO111MODULE=on 

jobs:
  include:
    - stage: "setup"
      name: "setup"
      script: make deps
    - stage: "compile"
      name: "compile"
      script: make build
    - stage: "tests"
      name: "tests"
      script: make test
