language: go

go:
  - "1.11.1"

go_import_path: github.com/kevinwmiller/digidoc

branches:
  only:
  - master
  - development

env:
  - GO111MODULE=on 

before_install:
  - ./vet.sh

before_script:
  - make deps