// Code generated by protoc-gen-go. DO NOT EDIT.
// source: digidoc.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Upload
type UploadMetaData struct {
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	ParentPath           string   `protobuf:"bytes,5,opt,name=parent_path,json=parentPath,proto3" json:"parent_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadMetaData) Reset()         { *m = UploadMetaData{} }
func (m *UploadMetaData) String() string { return proto.CompactTextString(m) }
func (*UploadMetaData) ProtoMessage()    {}
func (*UploadMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_digidoc_2ebdefbef1b2b87a, []int{0}
}
func (m *UploadMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadMetaData.Unmarshal(m, b)
}
func (m *UploadMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadMetaData.Marshal(b, m, deterministic)
}
func (dst *UploadMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadMetaData.Merge(dst, src)
}
func (m *UploadMetaData) XXX_Size() int {
	return xxx_messageInfo_UploadMetaData.Size(m)
}
func (m *UploadMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_UploadMetaData proto.InternalMessageInfo

func (m *UploadMetaData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UploadMetaData) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *UploadMetaData) GetParentPath() string {
	if m != nil {
		return m.ParentPath
	}
	return ""
}

type UploadRequest struct {
	Data                 []byte          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MetaData             *UploadMetaData `protobuf:"bytes,2,opt,name=metaData,proto3" json:"metaData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_digidoc_2ebdefbef1b2b87a, []int{1}
}
func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (dst *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(dst, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UploadRequest) GetMetaData() *UploadMetaData {
	if m != nil {
		return m.MetaData
	}
	return nil
}

type UploadResponse struct {
	Uuid                 uint64   `protobuf:"fixed64,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_digidoc_2ebdefbef1b2b87a, []int{2}
}
func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (dst *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(dst, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

func (m *UploadResponse) GetUuid() uint64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

// Browse
type BrowseRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrowseRequest) Reset()         { *m = BrowseRequest{} }
func (m *BrowseRequest) String() string { return proto.CompactTextString(m) }
func (*BrowseRequest) ProtoMessage()    {}
func (*BrowseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_digidoc_2ebdefbef1b2b87a, []int{3}
}
func (m *BrowseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseRequest.Unmarshal(m, b)
}
func (m *BrowseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseRequest.Marshal(b, m, deterministic)
}
func (dst *BrowseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseRequest.Merge(dst, src)
}
func (m *BrowseRequest) XXX_Size() int {
	return xxx_messageInfo_BrowseRequest.Size(m)
}
func (m *BrowseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseRequest proto.InternalMessageInfo

type BrowseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrowseResponse) Reset()         { *m = BrowseResponse{} }
func (m *BrowseResponse) String() string { return proto.CompactTextString(m) }
func (*BrowseResponse) ProtoMessage()    {}
func (*BrowseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_digidoc_2ebdefbef1b2b87a, []int{4}
}
func (m *BrowseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrowseResponse.Unmarshal(m, b)
}
func (m *BrowseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrowseResponse.Marshal(b, m, deterministic)
}
func (dst *BrowseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrowseResponse.Merge(dst, src)
}
func (m *BrowseResponse) XXX_Size() int {
	return xxx_messageInfo_BrowseResponse.Size(m)
}
func (m *BrowseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BrowseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BrowseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UploadMetaData)(nil), "grpc.UploadMetaData")
	proto.RegisterType((*UploadRequest)(nil), "grpc.UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "grpc.UploadResponse")
	proto.RegisterType((*BrowseRequest)(nil), "grpc.BrowseRequest")
	proto.RegisterType((*BrowseResponse)(nil), "grpc.BrowseResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DigiDocClient is the client API for DigiDoc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DigiDocClient interface {
	Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error)
	Browse(ctx context.Context, in *BrowseRequest, opts ...grpc.CallOption) (*BrowseResponse, error)
}

type digiDocClient struct {
	cc *grpc.ClientConn
}

func NewDigiDocClient(cc *grpc.ClientConn) DigiDocClient {
	return &digiDocClient{cc}
}

func (c *digiDocClient) Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error) {
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, "/grpc.DigiDoc/Upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digiDocClient) Browse(ctx context.Context, in *BrowseRequest, opts ...grpc.CallOption) (*BrowseResponse, error) {
	out := new(BrowseResponse)
	err := c.cc.Invoke(ctx, "/grpc.DigiDoc/Browse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DigiDocServer is the server API for DigiDoc service.
type DigiDocServer interface {
	Upload(context.Context, *UploadRequest) (*UploadResponse, error)
	Browse(context.Context, *BrowseRequest) (*BrowseResponse, error)
}

func RegisterDigiDocServer(s *grpc.Server, srv DigiDocServer) {
	s.RegisterService(&_DigiDoc_serviceDesc, srv)
}

func _DigiDoc_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigiDocServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DigiDoc/Upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigiDocServer).Upload(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigiDoc_Browse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrowseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigiDocServer).Browse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DigiDoc/Browse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigiDocServer).Browse(ctx, req.(*BrowseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DigiDoc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.DigiDoc",
	HandlerType: (*DigiDocServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _DigiDoc_Upload_Handler,
		},
		{
			MethodName: "Browse",
			Handler:    _DigiDoc_Browse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "digidoc.proto",
}

func init() { proto.RegisterFile("digidoc.proto", fileDescriptor_digidoc_2ebdefbef1b2b87a) }

var fileDescriptor_digidoc_2ebdefbef1b2b87a = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0xb7, 0x6e, 0xad, 0xfa, 0xd6, 0xae, 0x12, 0xf7, 0x10, 0xbc, 0x58, 0x82, 0x87, 0x9e,
	0x8a, 0xac, 0xf8, 0x07, 0xa4, 0x57, 0x41, 0x02, 0x7b, 0xf0, 0x24, 0xcf, 0x26, 0x74, 0x03, 0x6e,
	0x13, 0x9b, 0x94, 0xfe, 0x7d, 0x49, 0xd2, 0x8a, 0xbd, 0x0d, 0xc3, 0xfb, 0x66, 0x06, 0x1e, 0xe4,
	0x42, 0xb5, 0x4a, 0xe8, 0xa6, 0x32, 0xbd, 0x76, 0x9a, 0xa4, 0x6d, 0x6f, 0x1a, 0xf6, 0x01, 0xdb,
	0x83, 0xf9, 0xd6, 0x28, 0xde, 0xa4, 0xc3, 0x1a, 0x1d, 0x12, 0x02, 0x69, 0x87, 0x27, 0x49, 0xd7,
	0x45, 0x52, 0x5e, 0xf1, 0xa0, 0xbd, 0xe7, 0xb0, 0xb5, 0x34, 0x2d, 0xd6, 0xde, 0xf3, 0x9a, 0x3c,
	0xc0, 0xc6, 0x60, 0x2f, 0x3b, 0xf7, 0x69, 0xd0, 0x1d, 0xe9, 0x79, 0x38, 0x87, 0x68, 0xbd, 0xa3,
	0x3b, 0xb2, 0x03, 0xe4, 0x31, 0x9a, 0xcb, 0x9f, 0x41, 0x5a, 0xe7, 0x53, 0x04, 0x3a, 0xa4, 0x49,
	0x91, 0x94, 0xd7, 0x3c, 0x68, 0xf2, 0x04, 0x97, 0xa7, 0xa9, 0x99, 0x9e, 0x15, 0x49, 0xb9, 0xd9,
	0xef, 0x2a, 0x3f, 0xac, 0x5a, 0xae, 0xe2, 0x7f, 0x57, 0xec, 0x71, 0x5e, 0xcc, 0xa5, 0x35, 0xba,
	0xb3, 0x61, 0xdd, 0x30, 0x28, 0x11, 0x72, 0x33, 0x1e, 0x34, 0xbb, 0x81, 0xfc, 0xb5, 0xd7, 0xa3,
	0x95, 0x53, 0x39, 0xbb, 0x85, 0xed, 0x6c, 0x44, 0x6c, 0x3f, 0xc2, 0x45, 0xad, 0x5a, 0x55, 0xeb,
	0x86, 0xbc, 0x40, 0x16, 0x33, 0xc9, 0xdd, 0xff, 0xf6, 0x89, 0xbd, 0xdf, 0x2d, 0xcd, 0xc8, 0xb3,
	0x95, 0xc7, 0x62, 0xe6, 0x8c, 0x2d, 0x2a, 0x67, 0x6c, 0x59, 0xcb, 0x56, 0x5f, 0x59, 0x78, 0xc0,
	0xf3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0x2c, 0xcf, 0xaf, 0x91, 0x01, 0x00, 0x00,
}
